{{- define "basic-chart-api.deployments" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector: #used to select the pods
    matchLabels:
      app: {{ .Release.Name }} 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- with .Values.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
{{- end }}